// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package schema

import (
	"context"
)

const health = `-- name: Health :exec
SELECT 1
`

func (q *Queries) Health(ctx context.Context) error {
	_, err := q.db.Exec(ctx, health)
	return err
}
